title: DeepABIS
description: Deep Automated Bee Identification System
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
github:
  repository_name: DeepABIS
  repository_url: https://github.com/deepabis/deepabis
  owner_name: Flynamic
  owner_url: https://github.com/Flynamic
  is_project_page: true
paper:
  paper_url: https://doi.org/10.1016/j.ecoinf.2019.101017
